### ISSUE TITLE
"fi" / "fl" text formatting

### ISSUE THREAD

**Issue by burkekevinm** [omniphx/adminite#16]
Very minor issue but if you type fi (ex. file) in the query editor, the view updates and shows the fi smaller and running into each other. It also happens with lowercase FL.  Looks to be related to autoformatting. Doesn't affect functionality, just readability.

**Comment by omniphx** [comment]
Never noticed that before. I'm using Google's Space Mono and looks like it does "fi" thing on purpose:
![2019-11-01_00-10-02](https://user-images.githubusercontent.com/3722405/68001778-f4b0ac80-fc3b-11e9-85d7-a06dd1228c0b.gif)

I could probably swap out a new mono font pretty easily. Not strongly tied to Space Mono, plus it will probably go away when I build out a code editor for queries/syntax highlighting #4

**Comment by omniphx** [comment]
Updated the font in Version 0.1.5. No longer doing any weird character transformations
