### ISSUE TITLE
Object field list

### ISSUE THREAD

**Issue by burkekevinm** [omniphx/adminite#18]
When writing queries, I often have to figure out what the field name is for what I'm looking for. There's intellisense on the object names but not the fields. A nice feature (outside of the autocompletion) would maybe be if you selected an object in the query (ex double click, perhaps identifying also subquery relationships too) you could somehow pull up the complete field list to see all the fields (kind of similar to workbench dropdown). Sometimes fields have prefixes etc that make the autocomplete less useful vs just checking the list.

**Comment by omniphx** [comment]
Heard similar feedback. I was planning on converting the "Fill fields" into a popup with selectable fields.

Here's my simple prototype:
![2019-11-01_00-18-29](https://user-images.githubusercontent.com/3722405/68002042-355cf580-fc3d-11e9-8fab-2b31224b965b.png)

**Comment by burkekevinm** [comment]
I think the mockup is good. Have it by default have nothing selected but
then have a checkbox that would select all and insert.

>

**Comment by omniphx** [comment]
Added to Version 0.1.9
