### ISSUE TITLE
Export Query to Excel on PC

### ISSUE THREAD

**Issue by klabovitch35** [omniphx/adminite#2]
Currently, when exporting a query on a Windows Machine, the file is saved in downloads as an "Internet Explorer" Type file, rather than an Excel/CSV. This makes it difficult to transform/do anything with the export. PLEASE MARTY FIX IT NOW I KNOW YOU DON'T HAVE A LIFE OR GIRLFRIEND OR ANYTHING SO JUST DO ITTTTTTTTTTTT

**Comment by omniphx** [comment]
Looks like it might have to do with the library I'm using. Seems like a common issue. On my home computer (Windows 10), I would just add `.csv` manually and it would set the correct file type.

**Comment by omniphx** [comment]
@klabovitch35 can you confirm if is now fixed in Version 0.1.14?

**Comment by klabovitch35** [comment]
I..... both traded in my work pc and gave my old pc away to my little
brother....so I no longer can be your PC tester anymore :/.

**Comment by omniphx** [comment]
Oh right... forgot. I can test on my PC, thanks!

**Comment by omniphx** [comment]
I don't have excel on my PC but it seems to be saving to the correct format now. Closing unless it starts re-occurring.
