### ISSUE TITLE
Environment Authentication Leads to Ever-Loading Authentication Page

### ISSUE THREAD

**Issue by mikeandnemo** [omniphx/adminite#3]
Steps to reproduce:

1. Go to Adminite
2. Click New environment (top left option)
3. Set value for Name, Environment
4. Click Connect
5. See Browser window/tab open to authenticate 
6. Sign in or Choose user for that appropriate environment
7. See Browser forever-load until times out

Expected Outcome:

1. Environment is authenticated and available as selection in Adminite (This works!)
2. Browser tab closes or stops loading ¯\_(ツ)_/¯

**Comment by omniphx** [comment]
Looks like Salesforce is waiting for a response but Adminite has moved on with its life.

Should be an easy fix! :)

**Comment by omniphx** [comment]
Fixed in v0.0.9

**Comment by omniphx** [comment]
Currently redirects to https://adminite.app. Working on a landing page
