### ISSUE TITLE
Certain queries causing app to crash

### ISSUE THREAD

**Issue by burkekevinm** [omniphx/adminite#30]
When running an aggregate/group by query pasted in it shows a little red circle in the corner (guessing it's validating query formatting even though query runs fine in workbench soqooli) and when I run it it just goes white almost immediately like it crashes. 

When I took out the where clause it would run a little longer and then go to a white screen. When I took off the count and just returned the Id it worked. I'm thinking it's something in processing the aggregate values. I tried aliasing the count and that failed as well.

SELECT count(id) from Action_Sheet__c where reference1__c.reference__2.value__c IN ('0013Z000<value>')

This was after the latest update

**Comment by omniphx** [comment]
Thanks @burkekevinm !

Made some data-structuring changes but forgot to account for aggregate queries. Fix applied in 0.1.3
