### ISSUE TITLE
Feature: Pagination at top

### ISSUE THREAD

**Issue by burkekevinm** [omniphx/adminite#39]
Currently pagination is only at the bottom of the results. It would be useful (especially with higher page counts) to have pagination at the top as well to avoid having to go to the bottom of the results.

**Comment by omniphx** [comment]
Added to the top of the tables in Version 0.1.16

**Comment by burkekevinm** [comment]
It looks like in one of the updates you removed the little icons from the
query tabs and now show the object name. While I think the object name is
helpful I did like the small icons, especially when I have a few queries
where it's on the same object and I'm switching back and forth. It's not a
big deal but I do think there's a little value.

>

**Comment by omniphx** [comment]
Unfortunately, got a lot of feedback that the icons were not very popular :(

At some point, I'll build user settings and can give users the option to choose if they want iconsor sobject tab delimiters
