### ISSUE TITLE
Bulk Update cannot update more than 200 records at a time

### ISSUE THREAD

**Issue by dauus** [omniphx/adminite#45]
I queried the contact object using this type of query:
SELECT Id, Name, Email, AccountId
FROM Contact
WHERE EMAIL LIKE '%gmail.com'

I pulled over 1k results and set the max page size to 200.
I go to update and click bulk update -> and update the account id. 
I click apply and the accountid turned yellow.
Then I click save changes and nothing happened. 

I am curious if I am doing it right?

**Comment by omniphx** [comment]
Noticed a similar issue when updating large volume. I think it might just be taking a long time. Might look into breaking up the transactions into chunks.

Just FYI, the "Select all" box will select all results--not all per page. You can see many records you select in the popup box.

**Comment by omniphx** [comment]
Looks like the most records I can bulk update at a time is 200 records. Which is fine, just need to split up the transaction.

**Comment by omniphx** [comment]
Should be fixed in Version 0.1.21
