### ISSUE TITLE
Export performance

### ISSUE THREAD

**Issue by burkekevinm** [omniphx/adminite#47]
I've noticed a few times that export performance (after choosing type and folder) can be very slow intermittently.  This was on a Mac and trying to open finder/etc just has it spinning and adminite is frozen. It seems to happen after querying (and potentially) exporting a previous large dataset. Closing that large dataset tab doesn't seem to improve (guessing some memory leak perhaps). Save time was 2 minutes for a file that contained 60 rows. Previous export was 55k rows. Closing and reopening it executes basically immediately.

**Comment by burkekevinm** [comment]
It seems on recent builds that I've had a lot of performance issues with the export functionality. What's interesting is that the file exports pretty quickly (even small queries like 30 records) but the app freezes for about a minute and is unresponsive. After that time then it pops open the finder window and shows the file.

**Comment by burkekevinm** [comment]
Any updates on this item? I use adminite every day and this is the main issue that really affects things since it locks you out from querying when you do an export. Thanks!

**Comment by omniphx** [comment]
Hey @burkekevinm, glad to hear someone is still using adminite these days. I'll look into it when I get the chance but that might be a while. Currently tied up with other projects for the foreseeable future. I would probably recommend using workbench for exporting large datasets

**Comment by omniphx** [comment]
@burkekevinm, I've done a few things in version 0.3.6 to address this. Unfortunately, I don't have access to an org with a large dataset but I found a few things that might help with this. Let me know if it's still an issue in the latest release.

**Comment by burkekevinm** [comment]
Looks pretty similar to before. The csv exports immediately but it freezes up the finder in mac for minutes. The file can be copied off pretty much immediately. Could be something specific to my machine (not sure why) but it doesn't seem to happen on a friends windows machine. I don't seem to have issues with other applications saving/exporting.

**Comment by burkekevinm** [comment]
I tested it on 0.3.6 and it worked perfectly. The export completed quickly and did not lock up adminite or the finder. It appears to be resolved, thanks!

**Comment by omniphx** [comment]
Awesome, thanks for checking!
