### ISSUE TITLE
Settings for how tab is handled

### ISSUE THREAD

**Issue by burkekevinm** [omniphx/adminite#48]
This is an alternative to #31 for the shortcut execution. Currently the tab key actually inserts a Tab but I never use it for that and always use it for the Tab + Enter to execute the query (not supported in adminite). Depending on the other item, it would be nice to have some user/local preferences such as tab actually tabs to the query button vs \t and other potential preferences.

**Comment by omniphx** [comment]
Ability to disable tabbing in the query editor available in Version 0.1.22

![2019-12-22_20-54-54](https://user-images.githubusercontent.com/3722405/71330905-7961cd80-24fd-11ea-95ab-52a34caeb2a8.png)
![2019-12-22_20-54-25](https://user-images.githubusercontent.com/3722405/71330910-7e268180-24fd-11ea-93d7-f0a34b9791f7.png)
