### ISSUE TITLE
Bug: Add Fields - Selecting Fields from Multiple Filter fields selection Doesn't Apply when invalid query statement in editor

### ISSUE THREAD

**Issue by mikeandnemo** [omniphx/adminite#49]
Uber-low priority and definitely on the user....but logging for posterity

Preconditions:
1) Selected object in target object bar
2) Query Editor contained an invalid query "Select ID"

Steps to reproduce:

1) Click Add Fields
2) Enter value in 'Filter fields' bar
3) Select a field
4) Enter different value in 'Filter fields' bar
5) Select a field
6) Click Apply
7) See "Since your query is not valid, this will overwrite your current query. Are you sure you want to proceed?"
8) Click Yes
9) Nothing happens

**Comment by omniphx** [comment]
Am I missing a step?
![2019-12-21_15-11-55](https://user-images.githubusercontent.com/3722405/71313272-53a4cd80-2404-11ea-9bd8-daf019fc7029.gif)
