### ISSUE TITLE
Issues with search filters and dates

### ISSUE THREAD

**Issue by burkekevinm** [omniphx/adminite#56]
Filtering datetime and date values in the results does not work as expected. For example if you query on created date and the results has 01/02/2020 12:52PM and you try to filter on any part it will not show any results. It appears if you search on 2020-01-02 it will get the results but I tried doing 2020-01-06T1 or 2020-01-06 1 to search on the time and it filters out all results. I'm guessing it's filtering on the backend format vs the display format.

**Comment by omniphx** [comment]
Fixed in version 0.1.31
