### ISSUE TITLE
Do Not Treat 0% as NULL

### ISSUE THREAD

**Issue by mikeandnemo** [omniphx/adminite#57]
As a SF Data Scientist, I do not want 0% to be treated as NULL when querying because it may cause confusion and may require additional filtering between a null and an actual 0% value

**Comment by burkekevinm** [comment]
As a similar situation I noticed where we had a percentage that shows as 0.1999% in salesforce it converts on display to show 0%. It looks like it's doing some rounding logic on percentages and probably stripping any decimals and just rounding up/down.

**Comment by omniphx** [comment]
Released fix in Version 0.1.30
