### ISSUE TITLE
Allow client to be updated automatically/manually

### ISSUE THREAD

**Issue by elijahbun** [omniphx/adminite#9]
When a new version of adminite is released, user can be prompted to update or have an option for users to manually update to the latest version.

**Comment by omniphx** [comment]
Should happen automatically. Just close/re-open the app. Wait ~10 seconds and then a notification should pop up. After that it will instruct you to restart the app.

Unfortunately that's just how it works with Electron

**Comment by omniphx** [comment]
Now shows a link button at the bottom right when an update is available. Clicking it will install the latest update (if there is one) and restart the app.

Available in 0.1.19
